CREATE TABLE IF NOT EXISTS products(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  price REAL NOT NULL,
  stock INTEGER NOT NULL,
  lowStock INTEGER DEFAULT 5
);

CREATE TABLE IF NOT EXISTS sales(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  datetime TEXT,
  total REAL
);

CREATE TABLE IF NOT EXISTS sold_items(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  saleId INTEGER,
  productId INTEGER,
  quantity INTEGER,
  price REAL
);
